fast_exit:
  enabled: true
  phrases: ["goodbye robot"]
  fuzzy: 90            
  debounce_ms: 120     # anti-spam
  min_chars: 2
  confirm_tts:
    en: "See you later!"
    ro: "Bine, ne auzim mai t√¢rziu!"
    default: "See you later!"
  phrase_langs:
    "goodbye robot": "en"
  use_barge_check: true
  hotword:
    enabled: true
    engine: openwakeword
    model_path: "/home/delia/Conversational_Robot/Conversational_Bot/voices/goodbye_robot.onnx"
    threshold: 0.55
    min_gap_ms: 1200
    label: "goodbye robot"

stop_hotword:
  enabled: true
  engine: openwakeword
  model_path: "/home/delia/Conversational_Robot/Conversational_Bot/voices/stop_robot.onnx"
  threshold: 0.55
  min_gap_ms: 900
  label: "stop robot"
  mode: "barge"
